namespace csv_parser.Models
{
    class SeasonTemplate
    {
        string Season { get; set; }
        string Div { get; set; }
        string Date { get; set; }
        string HomeTeam { get; set; }
        string AwayTeam { get; set; }
        string FTHG { get; set; }
        string FTAG { get; set; }
        string FTR { get; set; }
        string HTHG { get; set; }
        string HTAG { get; set; }
        string HTR { get; set; }
        string Referee { get; set; }
        string HS { get; set; }
        string AS { get; set; }
        string HST { get; set; }
        string AST { get; set; }
        string HF { get; set; }
        string AF { get; set; }
        string HC { get; set; }
        string AC { get; set; }
        string HY { get; set; }
        string AY { get; set; }
        string HR { get; set; }
        string AR { get; set; }
        string B365H { get; set; }
        string B365D { get; set; }
        string B365A { get; set; }
        string BWH { get; set; }
        string BWD { get; set; }
        string BWA { get; set; }
        string GBH { get; set; }
        string GBD { get; set; }
        string GBA { get; set; }
        string IWH { get; set; }
        string IWD { get; set; }
        string IWA { get; set; }
        string LBH { get; set; }
        string LBD { get; set; }
        string LBA { get; set; }
        string SBH { get; set; }
        string SBD { get; set; }
        string SBA { get; set; }
        string WHH { get; set; }
        string WHD { get; set; }
        string WHA { get; set; }
        string SJH { get; set; }
        string SJD { get; set; }
        string SJA { get; set; }
        string VCH { get; set; }
        string VCD { get; set; }
        string VCA { get; set; }
        string Bb1X2 { get; set; }
        string BbMxH { get; set; }
        string BbAvH { get; set; }
        string BbMxD { get; set; }
        string BbAvD { get; set; }
        string BbMxA { get; set; }
        string BbAvA { get; set; }
        string BbOU { get; set; }
        string BbMxgt25 { get; set; }
        string BbAvgt25 { get; set; }
        string BbMxlt25 { get; set; }
        string BbAvlt25 { get; set; }
        string BbAH { get; set; }
        string BbAHh { get; set; }
        string BbMxAHH { get; set; }
        string BbAvAHH { get; set; }
        string BbMxAHA { get; set; }
        string BbAvAHA { get; set; }
    }
}
